name = input('what is your name : ')
print('%s'%name)
surname = input('what is your surname : ')
print('%s'%surname)
grade = input('enter grade : ')
print('%s'%grade)
code = input('enter code : ')
print('%s'%code)
