num1 = input('enter first number : ')
num2 = input('enter second number : ')
num3 = input('enter third number : ')
num4 = input('enter four number : ')
num5 = input('enter five number : ')
print('Float of %s Equal' %num1, float(num1))
print('complex of %s Equal' %num1, complex(num1))
print('Float of %s Equal' %num2, float(num2))
print('complex of %s Equal' %num2, complex(num2))
print('Float of %s Equal' %num3, float(num3))
print('complex of %s Equal' %num3, complex(num3))
print('Float of %s Equal' %num4, float(num4))
print('complex of %s Equal' %num4, complex(num4))
print('Float of %s Equal' %num5, float(num5))
print('complex of %s Equal' %num5, complex(num5))