a = input('Inpur Your First Number : ' )
b = input('Inpur Your Second Number : ' )
c = input('Inpur Your Third Number : ')
d = input('Inpur Your fourth Number : ')
e = input('Inpur Your fifth Number : ')
print('Float of %s Equal '%a ,float(a))
print('Complex of %s Equal ' %a , complex(a))
print('Float of %s Equal '%b ,float(b))
print('Complex of %s Equal ' %b , complex(b))
print('Float of %s Equal '%c ,float(c))
print('Complex of %s Equal ' %c , complex(c))
print('Float of %s Equal '%d ,float(d))
print('Complex of %s Equal ' %d , complex(d))
print('Float of %s Equal '%e ,float(e))
print('Complex of %s Equal ' %e , complex(e))